// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: cliente.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO cliente	(
	categoria_cliente, 
	telefone,
	email
	) VALUES ($1, $2, $3)
RETURNING id
`

type CreateClientParams struct {
	CategoriaCliente pgtype.Int4 `json:"categoria_cliente"`
	Telefone         string      `json:"telefone"`
	Email            string      `json:"email"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createClient, arg.CategoriaCliente, arg.Telefone, arg.Email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
