// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: conta.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :exec
INSERT INTO conta (id_cliente) VALUES ($1)
`

func (q *Queries) CreateAccount(ctx context.Context, idCliente uuid.UUID) error {
	_, err := q.db.Exec(ctx, createAccount, idCliente)
	return err
}
