// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: conta.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO conta (id_cliente) VALUES ($1)
RETURNING id
`

func (q *Queries) CreateAccount(ctx context.Context, idCliente uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAccount, idCliente)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
