// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CategoriaCliente struct {
	ID        int32       `json:"id"`
	Categoria pgtype.Text `json:"categoria"`
}

type Cliente struct {
	ID               uuid.UUID          `json:"id"`
	CategoriaCliente pgtype.Int4        `json:"categoria_cliente"`
	Password         []byte             `json:"password"`
	Telefone         string             `json:"telefone"`
	Email            string             `json:"email"`
	DataCadastro     pgtype.Timestamptz `json:"data_cadastro"`
}

type Contum struct {
	ID           uuid.UUID          `json:"id"`
	Saldo        pgtype.Numeric     `json:"saldo"`
	IDCliente    uuid.UUID          `json:"id_cliente"`
	DataAbertura pgtype.Timestamptz `json:"data_abertura"`
	Status       pgtype.Int4        `json:"status"`
}

type PessoaFisica struct {
	ID             uuid.UUID `json:"id"`
	IDCliente      uuid.UUID `json:"id_cliente"`
	NomeCompleto   string    `json:"nome_completo"`
	DataNascimento time.Time `json:"data_nascimento"`
	Cpf            string    `json:"cpf"`
}

type PessoaJuridica struct {
	ID           uuid.UUID `json:"id"`
	IDCliente    uuid.UUID `json:"id_cliente"`
	DataCriacao  time.Time `json:"data_criacao"`
	NomeFantasia string    `json:"nome_fantasia"`
	Cnpj         string    `json:"cnpj"`
}

type Session struct {
	Token  string    `json:"token"`
	Data   []byte    `json:"data"`
	Expiry time.Time `json:"expiry"`
}

type StatusContum struct {
	ID     int32       `json:"id"`
	Status pgtype.Text `json:"status"`
}

type TipoTransferencium struct {
	ID   int32       `json:"id"`
	Tipo pgtype.Text `json:"tipo"`
}

type Transferencium struct {
	ID                uuid.UUID          `json:"id"`
	IDConta           uuid.UUID          `json:"id_conta"`
	Valor             pgtype.Numeric     `json:"valor"`
	Tipo              int32              `json:"tipo"`
	DataTransferencia pgtype.Timestamptz `json:"data_transferencia"`
}
