// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pessoa_fisica.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPessoaFisica = `-- name: CreatePessoaFisica :exec
INSERT INTO pessoa_fisica(
	id_cliente,
	nome_completo,
	data_nascimento,
	cpf
) VALUES ($1, $2, $3, $4)
`

type CreatePessoaFisicaParams struct {
	IDCliente      uuid.UUID `json:"id_cliente"`
	NomeCompleto   string    `json:"nome_completo"`
	DataNascimento time.Time `json:"data_nascimento"`
	Cpf            string    `json:"cpf"`
}

func (q *Queries) CreatePessoaFisica(ctx context.Context, arg CreatePessoaFisicaParams) error {
	_, err := q.db.Exec(ctx, createPessoaFisica,
		arg.IDCliente,
		arg.NomeCompleto,
		arg.DataNascimento,
		arg.Cpf,
	)
	return err
}
