// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pessoa_juridica.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPessoaJuridica = `-- name: CreatePessoaJuridica :exec
INSERT INTO pessoa_juridica(
	id_cliente,
	data_criacao,
	nome_fantasia,
	cnpj
) VALUES ($1, $2, $3, $4)
`

type CreatePessoaJuridicaParams struct {
	IDCliente    uuid.UUID `json:"id_cliente"`
	DataCriacao  time.Time `json:"data_criacao"`
	NomeFantasia string    `json:"nome_fantasia"`
	Cnpj         string    `json:"cnpj"`
}

func (q *Queries) CreatePessoaJuridica(ctx context.Context, arg CreatePessoaJuridicaParams) error {
	_, err := q.db.Exec(ctx, createPessoaJuridica,
		arg.IDCliente,
		arg.DataCriacao,
		arg.NomeFantasia,
		arg.Cnpj,
	)
	return err
}
