// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: transferencia.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransferencia = `-- name: CreateTransferencia :exec
INSERT INTO transferencia (
	id_conta, 
	valor,
	tipo
) VALUES ( $1,$2, $3 )
`

type CreateTransferenciaParams struct {
	IDConta uuid.UUID      `json:"id_conta"`
	Valor   pgtype.Numeric `json:"valor"`
	Tipo    int32          `json:"tipo"`
}

func (q *Queries) CreateTransferencia(ctx context.Context, arg CreateTransferenciaParams) error {
	_, err := q.db.Exec(ctx, createTransferencia, arg.IDConta, arg.Valor, arg.Tipo)
	return err
}
